### Model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### Method
stage: sft
do_train: true
finetuning_type: full

### Dataset
dataset: cardgame_train
template: qwen
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### Output
output_dir: /data/jiacheng/system/cache/temp/icml2026/walking/LLM4CardGame/output/sft_full
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### Train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### Eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### DeepSpeed
deepspeed: /data/jiacheng/system/cache/temp/icml2026/walking/LLM4CardGame/configs/ds_z3_config.json
